version: 2.1
orbs:
  docker: circleci/docker@1.0.0
workflows:
  jobs:
    - build
    - deploy

jobs:
  build:
    docker/publish:
      image: $DOCKER_LOGIN/$CIRCLE_PROJECT_REPONAME
      tag: 'latest'
            

