version: 2.1
orbs:
  docker: circleci/docker@1.0.0


jobs:
  heroku:
    machine: 
      image: ubuntu-2004:202010-01
    working_directory: ~/dockerci
    steps:
      - checkout
      - run:
          name: Pull and tag image
          command: | 
            docker pull $DOCKER_LOGIN/$CIRCLE_PROJECT_REPONAME
            docker tag $DOCKER_LOGIN/$CIRCLE_PROJECT_REPONAME registry.heroku.com/$HEROKU_APP_NAME/web
      - run:
          name: Push to Heroku
          command: | 
            docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD
            docker push registry.heroku.com/$HEROKU_APP_NAME/web

      - run:
          name: Release
          command: | 
            heroku container:login
            heroku container:release web
    


workflows:
  deploy:
    jobs:
      - docker/publish:
          image: $DOCKER_LOGIN/$CIRCLE_PROJECT_REPONAME
          tag: 'latest'
      - heroku:
          requires:
            - docker/publish

